# app/templates/digest_template.py

from datetime import datetime


def create_html_digest(summary: str):

    today = datetime.now().strftime("%d %B %Y")

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">

        <style>

            body {{
                font-family: Arial, sans-serif;
                background-color: #f5f5f5;
                padding: 20px;
            }}

            .container {{
                max-width: 900px;
                margin: auto;
                background: white;
                padding: 30px;
                border-radius: 12px;
            }}

            .header {{
                text-align: center;
                margin-bottom: 30px;
            }}

            .title {{
                font-size: 32px;
                font-weight: bold;
            }}

            .date {{
                color: gray;
            }}

            .content {{
                line-height: 1.8;
                font-size: 16px;
            }}

            .content h1,
            .content h2,
            .content h3 {{
                margin-top: 25px;
            }}

            .content p {{
                margin-bottom: 15px;
            }}

            .content ul {{
                margin-left: 20px;
            }}

            .content li {{
                margin-bottom: 8px;
            }}

            .content strong {{
                font-weight: bold;
            }}

            .footer {{
                margin-top: 40px;
                color: gray;
                text-align: center;
            }}

        </style>

    </head>

    <body>

        <div class="container">

            <div class="header">

                <div class="title">
                    AI Daily Digest
                </div>

                <div class="date">
                    {today}
                </div>

            </div>

            <div class="content">
                {summary}
            </div>

            <div class="footer">
                Generated by AI News Aggregator
            </div>

        </div>

    </body>
    </html>
    """

    return html